#!/usr/bin/env python3
"""
Import processed JSON from content_pipeline to database.

This script imports processed tenders (generated by run_content_pipeline.py)
into the database. It appends to existing records without dropping anything.

Usage:
    # Import from default location
    python import_json_to_db.py

    # Import from custom file
    python import_json_to_db.py /path/to/processed_tenders.json

Examples:
    # After processing a new CSV file
    python run_content_pipeline.py new_tenders.csv
    python import_json_to_db.py

    # Import from specific location
    python import_json_to_db.py /data/output/processed_tenders.json
"""

import sys
from pathlib import Path
from app.services.pipeline.json_content_importer import JSONContentImporter
from app.database import SessionLocal

def main():
    """Import JSON file into database."""
    # Determine JSON file path
    if len(sys.argv) > 1:
        json_path = Path(sys.argv[1])
    else:
        # Default location after running run_content_pipeline.py
        json_path = Path('content_pipeline/output/processed_tenders.json')

    print("\n" + "="*80)
    print("JSON TO DATABASE IMPORT")
    print("="*80)

    if not json_path.exists():
        print(f"\n❌ File not found: {json_path}")
        print("\nUsage:")
        print("  python import_json_to_db.py")
        print("  python import_json_to_db.py /path/to/file.json")
        sys.exit(1)

    print(f"\n📥 Importing from: {json_path}")
    print(f"   File size: {json_path.stat().st_size / 1024 / 1024:.2f} MB")

    db = SessionLocal()
    try:
        importer = JSONContentImporter(db)
        print("\n⏳ Processing... this may take a moment")

        stats = importer.import_from_json(
            json_path,
            skip_if_already_generated=True  # Don't re-import already processed
        )

        print("\n" + "="*80)
        print("✅ IMPORT COMPLETE")
        print("="*80)
        print(f"\nResults:")
        print(f"  Total records in JSON:  {stats['total']}")
        print(f"  Successfully imported:  {stats['updated']}")
        print(f"  Already processed:      {stats['skipped']}")
        print(f"  Errors:                 {stats['errors']}")
        print(f"  With generated content: {stats['generated_count']}")

        if stats['updated'] > 0:
            print(f"\n✅ Successfully added {stats['updated']} tenders to database!")
            print("   Frontend can now access these via the API")
        elif stats['skipped'] > 0:
            print(f"\n⏭️  All {stats['skipped']} tenders already in database")
            print("   (Use --force flag to re-import)")
        else:
            print(f"\n⚠️  No tenders were imported")

        print("\n" + "="*80)

    except Exception as e:
        print(f"\n❌ Error during import: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        db.close()

if __name__ == '__main__':
    main()
