"""Initial schema: users, companies, tenders, alerts

Revision ID: 584db8bfcb5e
Revises: 
Create Date: 2025-10-23 09:37:56.337389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '584db8bfcb5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('region', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('source', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('published_date', sa.Date(), nullable=True))
    op.alter_column('tenders', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tenders', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_tenders_published_date'), 'tenders', ['published_date'], unique=False)
    op.create_index(op.f('ix_tenders_region'), 'tenders', ['region'], unique=False)
    op.drop_column('tenders', 'location')
    op.drop_column('tenders', 'ai_extracted_entities')
    op.drop_column('tenders', 'budget')
    op.drop_column('tenders', 'embedding_vector')
    op.drop_column('tenders', 'ai_summary')
    op.drop_column('tenders', 'raw_document_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('raw_document_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('embedding_vector', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('ai_extracted_entities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenders', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenders_region'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_published_date'), table_name='tenders')
    op.alter_column('tenders', 'deadline',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tenders', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('tenders', 'published_date')
    op.drop_column('tenders', 'source')
    op.drop_column('tenders', 'region')
    # ### end Alembic commands ###
