"""add_user_preferences_table_and_phone_field

Revision ID: 655187dea582
Revises: 993800b447a2
Create Date: 2025-11-06 14:14:02.127307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655187dea582'
down_revision = '993800b447a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_preferences table
    op.create_table('user_preferences',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('new_tender_alerts', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('deadline_reminders', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('weekly_digest', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('language', sa.String(length=10), nullable=False, server_default='en-US'),
        sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'),
        sa.Column('date_format', sa.String(length=20), nullable=False, server_default='MM/DD/YYYY'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)

    # Add phone column to users table
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
