"""Add Phase 4 pipeline tables and enhance Tender model

Revision ID: 993800b447a2
Revises: 584db8bfcb5e
Create Date: 2025-11-04 11:57:36.796623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993800b447a2'
down_revision = '584db8bfcb5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_id', sa.Integer(), nullable=False),
    sa.Column('existing_tender_id', sa.UUID(), nullable=False),
    sa.Column('detection_method', sa.String(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_details', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_logs_created_at'), 'duplicate_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_duplicate_logs_detection_method'), 'duplicate_logs', ['detection_method'], unique=False)
    op.create_index(op.f('ix_duplicate_logs_existing_tender_id'), 'duplicate_logs', ['existing_tender_id'], unique=False)
    op.create_index(op.f('ix_duplicate_logs_id'), 'duplicate_logs', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_logs_staging_id'), 'duplicate_logs', ['staging_id'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tenders_found', sa.Integer(), nullable=True),
    sa.Column('tenders_new', sa.Integer(), nullable=True),
    sa.Column('tenders_updated', sa.Integer(), nullable=True),
    sa.Column('tenders_validated', sa.Integer(), nullable=True),
    sa.Column('tenders_validation_failed', sa.Integer(), nullable=True),
    sa.Column('tenders_duplicate', sa.Integer(), nullable=True),
    sa.Column('tenders_transformed', sa.Integer(), nullable=True),
    sa.Column('tenders_loaded', sa.Integer(), nullable=True),
    sa.Column('extraction_time_seconds', sa.Float(), nullable=True),
    sa.Column('validation_time_seconds', sa.Float(), nullable=True),
    sa.Column('transformation_time_seconds', sa.Float(), nullable=True),
    sa.Column('deduplication_time_seconds', sa.Float(), nullable=True),
    sa.Column('loading_time_seconds', sa.Float(), nullable=True),
    sa.Column('total_pipeline_time_seconds', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_logs_id'), 'scrape_logs', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_logs_source'), 'scrape_logs', ['source'], unique=False)
    op.create_index(op.f('ix_scrape_logs_started_at'), 'scrape_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scrape_logs_status'), 'scrape_logs', ['status'], unique=False)
    op.create_table('tender_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('transformation_errors', sa.JSON(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of_tender_id', sa.UUID(), nullable=True),
    sa.Column('duplicate_reason', sa.String(), nullable=True),
    sa.Column('duplicate_similarity_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transformed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_staging_created_at'), 'tender_staging', ['created_at'], unique=False)
    op.create_index(op.f('ix_tender_staging_id'), 'tender_staging', ['id'], unique=False)
    op.create_index(op.f('ix_tender_staging_is_duplicate'), 'tender_staging', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_tender_staging_scrape_run_id'), 'tender_staging', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_tender_staging_source_id'), 'tender_staging', ['source_id'], unique=False)
    op.create_index(op.f('ix_tender_staging_status'), 'tender_staging', ['status'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staging_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staging_id'], ['tender_staging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_errors_created_at'), 'validation_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_validation_errors_error_type'), 'validation_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_validation_errors_id'), 'validation_errors', ['id'], unique=False)
    op.create_index(op.f('ix_validation_errors_scrape_run_id'), 'validation_errors', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_validation_errors_severity'), 'validation_errors', ['severity'], unique=False)
    op.create_index(op.f('ix_validation_errors_staging_id'), 'validation_errors', ['staging_id'], unique=False)
    op.add_column('tenders', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('budget_currency', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('tenders', sa.Column('data_quality_score', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenders', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenders', sa.Column('scrape_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tenders_content_hash'), 'tenders', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tenders_external_id'), 'tenders', ['external_id'], unique=True)
    op.create_index(op.f('ix_tenders_source'), 'tenders', ['source'], unique=False)
    op.create_index(op.f('ix_tenders_source_url'), 'tenders', ['source_url'], unique=True)
    op.create_foreign_key(None, 'tenders', 'scrape_logs', ['scrape_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenders', type_='foreignkey')
    op.drop_index(op.f('ix_tenders_source_url'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_source'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_external_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_content_hash'), table_name='tenders')
    op.drop_column('tenders', 'scrape_run_id')
    op.drop_column('tenders', 'last_verified_at')
    op.drop_column('tenders', 'scraped_at')
    op.drop_column('tenders', 'data_quality_score')
    op.drop_column('tenders', 'content_hash')
    op.drop_column('tenders', 'external_id')
    op.drop_column('tenders', 'budget_currency')
    op.drop_column('tenders', 'budget')
    op.drop_index(op.f('ix_validation_errors_staging_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_severity'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_scrape_run_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_id'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_error_type'), table_name='validation_errors')
    op.drop_index(op.f('ix_validation_errors_created_at'), table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index(op.f('ix_tender_staging_status'), table_name='tender_staging')
    op.drop_index(op.f('ix_tender_staging_source_id'), table_name='tender_staging')
    op.drop_index(op.f('ix_tender_staging_scrape_run_id'), table_name='tender_staging')
    op.drop_index(op.f('ix_tender_staging_is_duplicate'), table_name='tender_staging')
    op.drop_index(op.f('ix_tender_staging_id'), table_name='tender_staging')
    op.drop_index(op.f('ix_tender_staging_created_at'), table_name='tender_staging')
    op.drop_table('tender_staging')
    op.drop_index(op.f('ix_scrape_logs_status'), table_name='scrape_logs')
    op.drop_index(op.f('ix_scrape_logs_started_at'), table_name='scrape_logs')
    op.drop_index(op.f('ix_scrape_logs_source'), table_name='scrape_logs')
    op.drop_index(op.f('ix_scrape_logs_id'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_duplicate_logs_staging_id'), table_name='duplicate_logs')
    op.drop_index(op.f('ix_duplicate_logs_id'), table_name='duplicate_logs')
    op.drop_index(op.f('ix_duplicate_logs_existing_tender_id'), table_name='duplicate_logs')
    op.drop_index(op.f('ix_duplicate_logs_detection_method'), table_name='duplicate_logs')
    op.drop_index(op.f('ix_duplicate_logs_created_at'), table_name='duplicate_logs')
    op.drop_table('duplicate_logs')
    # ### end Alembic commands ###
