"""add company tender profiles and user interactions tables

Revision ID: ae041464a9f5
Revises: content_gen_001
Create Date: 2025-12-25 11:34:57.957451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'ae041464a9f5'
down_revision = 'content_gen_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    op.create_table('company_tender_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('primary_sector', sa.String(length=100), nullable=False),
    sa.Column('active_sectors', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('sub_sectors', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('preferred_regions', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('company_size', sa.String(length=20), nullable=True),
    sa.Column('years_in_operation', sa.String(length=10), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('budget_min', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('budget_max', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('discovered_interests', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_sources', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_languages', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_deadline_days', sa.Integer(), nullable=True),
    sa.Column('min_match_threshold', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('scoring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_embedding', Vector(1024), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_company_tender_profiles_primary_sector'), 'company_tender_profiles', ['primary_sector'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('interaction_weight', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('match_score_at_time', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tender_category', sa.String(length=100), nullable=True),
    sa.Column('tender_region', sa.String(length=100), nullable=True),
    sa.Column('tender_budget', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('feedback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', 'interaction_type', name='unique_user_tender_interaction')
    )
    op.create_index(op.f('ix_user_interactions_created_at'), 'user_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_interactions_interaction_type'), 'user_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interactions_tender_id'), 'user_interactions', ['tender_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_user_id'), 'user_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_interactions_user_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_tender_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_interaction_type'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_created_at'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_company_tender_profiles_primary_sector'), table_name='company_tender_profiles')
    op.drop_table('company_tender_profiles')
    # ### end Alembic commands ###
