"""
Pydantic schemas for tender-related requests and responses.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict
from uuid import UUID
from datetime import date, datetime
from enum import Enum


# ==================== Enums ====================

class TenderStatus(str, Enum):
    """
    Tender status enum.
    """
    DRAFT = "draft"
    PUBLISHED = "published"
    CLOSED = "closed"
    CANCELLED = "cancelled"


# ==================== Request Schemas ====================

class TenderCreate(BaseModel):
    """
    Schema for tender creation request.
    """
    title: str = Field(..., min_length=5, max_length=500, description="Tender title")
    description: str = Field(..., min_length=10, description="Tender description")
    category: Optional[str] = Field(None, max_length=100, description="Tender category (e.g., IT, Construction)")
    region: Optional[str] = Field(None, max_length=100, description="Tender region/location")
    source: Optional[str] = Field(None, max_length=200, description="Tender source")
    source_url: Optional[str] = Field(None, description="URL to original tender document")
    published_date: Optional[date] = Field(None, description="Date when tender was published")
    deadline: Optional[date] = Field(None, description="Tender submission deadline")
    status: TenderStatus = Field(default=TenderStatus.PUBLISHED, description="Tender status")


class TenderUpdate(BaseModel):
    """
    Schema for tender update request.
    """
    title: Optional[str] = Field(None, min_length=5, max_length=500, description="Tender title")
    description: Optional[str] = Field(None, min_length=10, description="Tender description")
    category: Optional[str] = Field(None, max_length=100, description="Tender category")
    region: Optional[str] = Field(None, max_length=100, description="Tender region/location")
    source: Optional[str] = Field(None, max_length=200, description="Tender source")
    source_url: Optional[str] = Field(None, description="URL to original tender document")
    published_date: Optional[date] = Field(None, description="Date when tender was published")
    deadline: Optional[date] = Field(None, description="Tender submission deadline")
    status: Optional[TenderStatus] = Field(None, description="Tender status")


class TenderFilter(BaseModel):
    """
    Schema for tender filtering and pagination.
    """
    category: Optional[str] = Field(None, description="Filter by category")
    region: Optional[str] = Field(None, description="Filter by region")
    status: Optional[TenderStatus] = Field(None, description="Filter by status")
    search: Optional[str] = Field(None, description="Search in title and description")

    # Date filters
    published_from: Optional[date] = Field(None, description="Filter tenders published from this date")
    published_to: Optional[date] = Field(None, description="Filter tenders published until this date")
    deadline_from: Optional[date] = Field(None, description="Filter tenders with deadline from this date")
    deadline_to: Optional[date] = Field(None, description="Filter tenders with deadline until this date")

    # Pagination
    skip: int = Field(default=0, ge=0, description="Number of records to skip")
    limit: int = Field(default=20, ge=1, le=100, description="Number of records to return")


# ==================== Response Schemas ====================

class TenderResponse(BaseModel):
    """
    Schema for tender response.
    """
    id: UUID
    title: str
    description: str
    category: Optional[str] = None
    region: Optional[str] = None
    source: Optional[str] = None
    source_url: Optional[str] = None
    published_date: Optional[date] = None
    deadline: Optional[date] = None
    status: TenderStatus
    created_at: datetime
    updated_at: datetime

    # Generated Content Fields (Content Generator)
    clean_description: Optional[str] = Field(None, description="LLM-generated clean description")
    highlights: Optional[str] = Field(None, description="LLM-generated key highlights")
    extracted_data: Optional[Dict] = Field(None, description="Structured extracted data (financial, contact, dates, requirements, specifications, organization, addresses)")
    content_generated_at: Optional[datetime] = Field(None, description="When content was generated by LLM")
    content_generation_errors: Optional[List[Dict]] = Field(None, description="Any errors during content generation")

    # AI Processing Fields (Phase 2)
    ai_summary: Optional[str] = Field(None, description="AI-generated summary")
    ai_processed: bool = Field(default=False, description="Whether AI processing is complete")
    ai_processed_at: Optional[datetime] = Field(None, description="When AI processing completed")
    extracted_entities: Optional[Dict] = Field(None, description="Extracted entities (deadline, budget, requirements, etc.)")
    raw_text: Optional[str] = Field(None, description="Extracted text from PDF/DOC")
    word_count: Optional[int] = Field(None, description="Document word count")

    model_config = ConfigDict(from_attributes=True)


class TenderListResponse(BaseModel):
    """
    Schema for paginated tender list response.
    """
    total: int = Field(..., description="Total number of tenders matching filter")
    items: List[TenderResponse] = Field(..., description="List of tenders")
    skip: int = Field(..., description="Number of records skipped")
    limit: int = Field(..., description="Number of records returned")


class TenderWithScore(TenderResponse):
    """
    Schema for tender response with relevance score.
    Used when returning personalized recommendations.
    """
    relevance_score: float = Field(..., description="Relevance score 0-100")
    match_breakdown: Dict = Field(..., description="Detailed score breakdown")
    match_explanation: str = Field(..., description="Human-readable explanation of match")

    model_config = ConfigDict(from_attributes=True)


class TenderWithScoreListResponse(BaseModel):
    """
    Schema for paginated tender list with scores.
    """
    total: int = Field(..., description="Total number of tenders matching filter")
    items: List[TenderWithScore] = Field(..., description="List of tenders with scores")
    skip: int = Field(..., description="Number of records skipped")
    limit: int = Field(..., description="Number of records returned")
